sudo: false
language: python
dist: xenial
python:
  - 2.7
  - 3.6
  - 3.7
matrix:
  include:
    - dist: trusty
      python: 2.6
addons:
  apt:
    packages:
    - swig
cache:
  pip: true
install:
  - pip install coverage
script:
  - nosetests --with-coverage --cover-branches # Test with pure Python tokenizer
  - CFLAGS="-coverage" python setup.py build_ext --inplace -t build
  - nosetests --with-coverage --cover-branches # Test with C tokenizer
  - gcov -o build/src/ src/ihm_format.c
after_success:
  - bash <(curl -s https://codecov.io/bash)
